/*

//v1.0
//Copyright 2006 Adobe Systems, Inc. All rights reserved.
*/
function AC_AddExtension(a,f){return-1!=a.indexOf("?")?a.replace(/\?/,f+"?"):a+f}function AC_Generateobj(a,f,g){var e="<object ",c;for(c in a)e+=c+'="'+a[c]+'" ';e+=">";for(c in f)e+='<param name="'+c+'" value="'+f[c]+'" /> ';e+="<embed ";for(c in g)e+=c+'="'+g[c]+'" ';document.write(e+" ></embed></object>")}
function AC_FL_RunContent(){var a=AC_GetArgs(arguments,".swf","movie","clsid:d27cdb6e-ae6d-11cf-96b8-444553540000","application/x-shockwave-flash");AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}function AC_SW_RunContent(){var a=AC_GetArgs(arguments,".dcr","src","clsid:166B1BCA-3F9C-11CF-8075-444553540000",null);AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}
function AC_GetArgs(a,f,g,e,c){for(var d={embedAttrs:{},params:{},objAttrs:{}},b=0;b<a.length;b+=2)switch(a[b].toLowerCase()){case "classid":break;case "pluginspage":d.embedAttrs[a[b]]=a[b+1];break;case "src":case "movie":0<=a[b+1].indexOf("/itslearnin.hs.llnwd.net/e1/")&&(a[b+1]=a[b+1].replace("/itslearnin.hs.llnwd.net/e1/","/statics.itslearning.com/"));a[b+1]=AC_AddExtension(a[b+1],f);d.embedAttrs.src=a[b+1];d.params[g]=a[b+1];break;case "onafterupdate":case "onbeforeupdate":case "onblur":case "oncellchange":case "onclick":case "ondblClick":case "ondrag":case "ondragend":case "ondragenter":case "ondragleave":case "ondragover":case "ondrop":case "onfinish":case "onfocus":case "onhelp":case "onmousedown":case "onmouseup":case "onmouseover":case "onmousemove":case "onmouseout":case "onkeypress":case "onkeydown":case "onkeyup":case "onload":case "onlosecapture":case "onpropertychange":case "onreadystatechange":case "onrowsdelete":case "onrowenter":case "onrowexit":case "onrowsinserted":case "onstart":case "onscroll":case "onbeforeeditfocus":case "onactivate":case "onbeforedeactivate":case "ondeactivate":case "type":case "codebase":d.objAttrs[a[b]]=
a[b+1];break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "id":case "tabindex":d.embedAttrs[a[b]]=d.objAttrs[a[b]]=a[b+1];break;default:d.embedAttrs[a[b]]=d.params[a[b]]=a[b+1]}d.objAttrs.classid=e;c&&(d.embedAttrs.type=c);return d};
