/*
 Knockout JavaScript library v3.5.0
 (c) The Knockout.js team - http://knockoutjs.com/
 License: MIT (http://www.opensource.org/licenses/mit-license.php)
*/
(function(){(function(q){var y=this||(0,eval)("this"),w=y.document,T=y.navigator,u=y.jQuery,F=y.JSON;u||"undefined"===typeof jQuery||(u=jQuery);(function(q){"function"===typeof define&&define.amd?define(["exports","require"],q):"object"===typeof exports&&"object"===typeof module?q(module.exports||exports):q(y.ko={})})(function(U,V){function J(a,c){return null===a||typeof a in X?a===c:!1}function Y(b,c){var d;return function(){d||(d=a.a.setTimeout(function(){d=q;b()},c))}}function Z(b,c){var d;return function(){clearTimeout(d);
d=a.a.setTimeout(b,c)}}function aa(a,c){c&&"change"!==c?"beforeChange"===c?this.oc(a):this.bb(a,c):this.pc(a)}function ba(a,c){null!==c&&c.s&&c.s()}function ca(a,c){var b=this.pd,e=b[t];e.qa||(this.Pb&&this.kb[c]?(b.tc(c,a,this.kb[c]),this.kb[c]=null,--this.Pb):e.F[c]||b.tc(c,a,e.G?{da:a}:b.Zc(a)),a.Ka&&a.fd())}var a="undefined"!==typeof U?U:{};a.b=function(b,c){b=b.split(".");for(var d=a,e=0;e<b.length-1;e++)d=d[b[e]];d[b[b.length-1]]=c};a.J=function(a,c,d){a[c]=d};a.version="3.5.0";a.b("version",
a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1,foreachHidesDestroyed:!1};a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}function e(b,c,d,e){var v=b[c].match(p)||[];a.a.C(d.match(p),function(b){a.a.Oa(v,b,e)});b[c]=v.join(" ")}var f=Object.prototype.hasOwnProperty,g={__proto__:[]}instanceof Array,l="function"===typeof Symbol,m={},k={};m[T&&/Firefox\/2/i.test(T.userAgent)?
"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];m.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(m,function(a,b){if(b.length)for(var c=0,d=b.length;c<d;c++)k[b[c]]=a});var h={propertychange:!0},n=w&&function(){for(var a=3,b=w.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:q}(),p=/\S+/g,r;return{Ic:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],
C:function(a,b,c){for(var d=0,e=a.length;d<e;d++)b.call(c,a[d],d,a)},A:"function"==typeof Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},Lb:function(a,b,c){for(var d=0,e=a.length;d<e;d++)if(b.call(c,a[d],d,a))return a[d];return q},hb:function(b,c){c=a.a.A(b,c);0<c?b.splice(c,1):0===c&&b.shift()},vc:function(b){var c=[];b&&a.a.C(b,function(b){0>a.a.A(c,b)&&c.push(b)});return c},Mb:function(a,
b,c){var d=[];if(a)for(var e=0,v=a.length;e<v;e++)d.push(b.call(c,a[e],e));return d},fb:function(a,b,c){var d=[];if(a)for(var e=0,v=a.length;e<v;e++)b.call(c,a[e],e)&&d.push(a[e]);return d},gb:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},Oa:function(b,c,d){var e=a.a.A(a.a.$b(b),c);0>e?d&&b.push(c):d||b.splice(e,1)},Ba:g,extend:c,setPrototypeOf:d,zb:g?d:c,O:b,Ha:function(a,b,c){if(!a)return a;var d={},e;for(e in a)f.call(a,e)&&(d[e]=
b.call(c,a[e],e,a));return d},Sb:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},Xb:function(b){b=a.a.la(b);for(var c=(b[0]&&b[0].ownerDocument||w).createElement("div"),d=0,e=b.length;d<e;d++)c.appendChild(a.na(b[d]));return c},Ca:function(b,c){for(var d=0,e=b.length,h=[];d<e;d++){var v=b[d].cloneNode(!0);h.push(c?a.na(v):v)}return h},ua:function(b,c){a.a.Sb(b);if(c)for(var d=0,e=c.length;d<e;d++)b.appendChild(c[d])},Wc:function(b,c){b=b.nodeType?[b]:b;if(0<b.length){for(var d=b[0],e=d.parentNode,
h=0,v=c.length;h<v;h++)e.insertBefore(c[h],d);h=0;for(v=b.length;h<v;h++)a.removeNode(b[h])}},Ua:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1<a.length&&a[a.length-1].parentNode!==b;)a.length--;if(1<a.length){b=a[0];var c=a[a.length-1];for(a.length=0;b!==c;)a.push(b),b=b.nextSibling;a.push(c)}}return a},Yc:function(a,b){7>n?a.setAttribute("selected",b):a.selected=b},Cb:function(a){return null===a||a===q?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,
"")},Td:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},ud:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Rb:function(b){return a.a.ud(b,b.ownerDocument.documentElement)},jd:function(b){return!!a.a.Lb(b,a.a.Rb)},P:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},zc:function(b){return a.onError?
function(){try{return b.apply(this,arguments)}catch(z){throw a.onError&&a.onError(z),z;}}:b},setTimeout:function(b,c){return setTimeout(a.a.zc(b),c)},Fc:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},H:function(b,c,d){var e=a.a.zc(d);d=h[c];if(a.options.useOnlyNativeEvents||d||!u)if(d||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var k=function(a){e.call(b,a)},f="on"+c;b.attachEvent(f,k);a.a.I.za(b,function(){b.detachEvent(f,k)})}else throw Error("Browser doesn't support addEventListener or attachEvent");
else b.addEventListener(c,e,!1);else r||(r="function"==typeof u(b).on?"on":"bind"),u(b)[r](c,e)},Fb:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.a.P(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(a.options.useOnlyNativeEvents||!u||d)if("function"==typeof w.createEvent)if("function"==typeof b.dispatchEvent)d=w.createEvent(k[c]||"HTMLEvents"),d.initEvent(c,!0,!0,y,0,0,0,0,0,!1,!1,!1,!1,0,b),
b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");else u(b).trigger(c)},c:function(b){return a.N(b)?b():b},$b:function(b){return a.N(b)?b.w():b},Eb:function(b,c,d){var h;c&&("object"===typeof b.classList?(h=b.classList[d?"add":"remove"],a.a.C(c.match(p),function(a){h.call(b.classList,a)})):"string"===typeof b.className.baseVal?
e(b.className,"baseVal",c,d):e(b,"className",c,d))},Ab:function(b,c){c=a.a.c(c);if(null===c||c===q)c="";var d=a.h.firstChild(b);!d||3!=d.nodeType||a.h.nextSibling(d)?a.h.ua(b,[b.ownerDocument.createTextNode(c)]):d.data=c;a.a.zd(b)},Xc:function(a,b){a.name=b;if(7>=n)try{var c=a.name.replace(/[&<>'"]/g,function(a){return"&#"+a.charCodeAt(0)+";"});a.mergeAttributes(w.createElement("<input name='"+c+"'/>"),!1)}catch(M){}},zd:function(a){9<=n&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},
vd:function(a){if(n){var b=a.style.width;a.style.width=0;a.style.width=b}},Od:function(b,c){b=a.a.c(b);c=a.a.c(c);for(var d=[];b<=c;b++)d.push(b);return d},la:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},Da:function(a){return l?Symbol(a):a},Xd:6===n,Yd:7===n,W:n,Kc:function(b,c){b=a.a.la(b.getElementsByTagName("input")).concat(a.a.la(b.getElementsByTagName("textarea")));for(var d="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},e=[],h=
b.length-1;0<=h;h--)d(b[h])&&e.push(b[h]);return e},Md:function(b){return"string"==typeof b&&(b=a.a.Cb(b))?F&&F.parse?F.parse(b):(new Function("return "+b))():null},fc:function(b,c,d){if(!F||!F.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return F.stringify(a.a.c(b),c,d)},Nd:function(c,d,e){e=e||{};var h=e.params||{},k=
e.includeFields||this.Ic,f=c;if("object"==typeof c&&"form"===a.a.P(c)){f=c.action;for(var l=k.length-1;0<=l;l--)for(var g=a.a.Kc(c,k[l]),m=g.length-1;0<=m;m--)h[g[m].name]=g[m].value}d=a.a.c(d);var n=w.createElement("form");n.style.display="none";n.action=f;n.method="post";for(var p in d)c=w.createElement("input"),c.type="hidden",c.name=p,c.value=a.a.fc(a.a.c(d[p])),n.appendChild(c);b(h,function(a,b){var c=w.createElement("input");c.type="hidden";c.name=a;c.value=b;n.appendChild(c)});w.body.appendChild(n);
e.submitter?e.submitter(n):n.submit();setTimeout(function(){n.parentNode.removeChild(n)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.C);a.b("utils.arrayFirst",a.a.Lb);a.b("utils.arrayFilter",a.a.fb);a.b("utils.arrayGetDistinctValues",a.a.vc);a.b("utils.arrayIndexOf",a.a.A);a.b("utils.arrayMap",a.a.Mb);a.b("utils.arrayPushAll",a.a.gb);a.b("utils.arrayRemoveItem",a.a.hb);a.b("utils.cloneNodes",a.a.Ca);a.b("utils.createSymbolOrString",a.a.Da);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",
a.a.Ic);a.b("utils.getFormFields",a.a.Kc);a.b("utils.objectMap",a.a.Ha);a.b("utils.peekObservable",a.a.$b);a.b("utils.postJson",a.a.Nd);a.b("utils.parseJson",a.a.Md);a.b("utils.registerEventHandler",a.a.H);a.b("utils.stringifyJson",a.a.fc);a.b("utils.range",a.a.Od);a.b("utils.toggleDomNodeCssClass",a.a.Eb);a.b("utils.triggerEvent",a.a.Fb);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.O);a.b("utils.addOrRemoveItem",a.a.Oa);a.b("utils.setTextContent",a.a.Ab);a.b("unwrap",a.a.c);
Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if(1===arguments.length)return function(){return b.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,1);return function(){var c=d.slice(0);c.push.apply(c,arguments);return b.apply(a,c)}});a.a.g=new function(){var b=0,c="__ko__"+(new Date).getTime(),d={},e,f;a.a.W?(e=function(a,e){var f=a[c];if(!f||"null"===f||!d[f]){if(!e)return q;f=a[c]="ko"+b++;d[f]={}}return d[f]},f=function(a){var b=a[c];return b?(delete d[b],
a[c]=null,!0):!1}):(e=function(a,b){var d=a[c];!d&&b&&(d=a[c]={});return d},f=function(a){return a[c]?(delete a[c],!0):!1});return{get:function(a,b){return(a=e(a,!1))&&a[b]},set:function(a,b,c){(a=e(a,c!==q))&&(a[b]=c)},Tb:function(a,b,c){a=e(a,!0);return a[b]||(a[b]=c)},clear:f,Z:function(){return b++ +c}}};a.b("utils.domData",a.a.g);a.b("utils.domData.clear",a.a.g.clear);a.a.I=new function(){function b(b,c){var d=a.a.g.get(b,e);d===q&&c&&(d=[],a.a.g.set(b,e,d));return d}function c(c){var e=b(c,
!1);if(e){e=e.slice(0);for(var k=0;k<e.length;k++)e[k](c)}a.a.g.clear(c);a.a.I.cleanExternalData(c);g[c.nodeType]&&d(c.childNodes,!0)}function d(b,d){for(var e=[],h,f=0;f<b.length;f++)if(!d||8===b[f].nodeType)if(c(e[e.length]=h=b[f]),b[f]!==h)for(;f--&&-1==a.a.A(e,b[f]););}var e=a.a.g.Z(),f={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{za:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},xb:function(c,d){var f=b(c,!1);f&&(a.a.hb(f,d),0==f.length&&a.a.g.set(c,
e,q))},na:function(a){f[a.nodeType]&&(c(a),g[a.nodeType]&&d(a.getElementsByTagName("*")));return a},removeNode:function(b){a.na(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){u&&"function"==typeof u.cleanData&&u.cleanData([a])}}};a.na=a.a.I.na;a.removeNode=a.a.I.removeNode;a.b("cleanNode",a.na);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.I);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.I.za);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.I.xb);
(function(){var b=[0,"",""],c=[1,"<table>","</table>"],d=[3,"<table><tbody><tr>","</tr></tbody></table>"],e=[1,"<select multiple='multiple'>","</select>"],f={thead:c,tbody:c,tfoot:c,tr:[2,"<table><tbody>","</tbody></table>"],td:d,th:d,option:e,optgroup:e},g=8>=a.a.W;a.a.ta=function(c,d){if(u)if(u.parseHTML)var e=u.parseHTML(c,d)||[];else{if((e=u.clean([c],d))&&e[0]){for(d=e[0];d.parentNode&&11!==d.parentNode.nodeType;)d=d.parentNode;d.parentNode&&d.parentNode.removeChild(d)}}else{(e=d)||(e=w);d=e.parentWindow||
e.defaultView||y;var h=a.a.Cb(c).toLowerCase(),n=e.createElement("div");var p=(h=h.match(/^(?:\x3c!--.*?--\x3e\s*?)*?<([a-z]+)[\s>]/))&&f[h[1]]||b;h=p[0];p="ignored<div>"+p[1]+c+p[2]+"</div>";for("function"==typeof d.innerShiv?n.appendChild(d.innerShiv(p)):(g&&e.body.appendChild(n),n.innerHTML=p,g&&n.parentNode.removeChild(n));h--;)n=n.lastChild;e=a.a.la(n.lastChild.childNodes)}return e};a.a.Ld=function(b,c){b=a.a.ta(b,c);return b.length&&b[0].parentElement||a.a.Xb(b)};a.a.dc=function(b,c){a.a.Sb(b);
c=a.a.c(c);if(null!==c&&c!==q)if("string"!=typeof c&&(c=c.toString()),u)u(b).html(c);else{c=a.a.ta(c,b.ownerDocument);for(var d=0;d<c.length;d++)b.appendChild(c[d])}}})();a.b("utils.parseHtmlFragment",a.a.ta);a.b("utils.setHtml",a.a.dc);a.aa=function(){function b(c,e){if(c)if(8==c.nodeType){var d=a.aa.Tc(c.nodeValue);null!=d&&e.push({sd:c,Jd:d})}else if(1==c.nodeType){d=0;c=c.childNodes;for(var g=c.length;d<g;d++)b(c[d],e)}}var c={};return{Wb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");
var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},ad:function(a,b){var d=c[a];if(d===q)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return d.apply(null,b||[]),!0}finally{delete c[a]}},bd:function(c,e){var d=[];b(c,d);c=0;for(var g=d.length;c<g;c++){var l=d[c].sd,m=[l];e&&a.a.gb(m,e);a.aa.ad(d[c].Jd,m);l.nodeValue="";l.parentNode&&
l.parentNode.removeChild(l)}},Tc:function(a){return(a=a.match(/^\[ko_memo:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.aa);a.b("memoization.memoize",a.aa.Wb);a.b("memoization.unmemoize",a.aa.ad);a.b("memoization.parseMemoText",a.aa.Tc);a.b("memoization.unmemoizeDomNodeAndDescendants",a.aa.bd);a.ma=function(){function b(){if(f)for(var b=f,c=0,d;l<f;)if(d=e[l++]){if(l>b){if(5E3<=++c){l=f;a.a.Fc(Error("'Too much recursion' after processing "+c+" task groups."));break}b=f}try{d()}catch(n){a.a.Fc(n)}}}
function c(){b();l=f=e.length=0}var d,e=[],f=0,g=1,l=0;y.MutationObserver?d=function(a){var b=w.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(c):d=w&&"onreadystatechange"in w.createElement("script")?function(a){var b=w.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;w.documentElement.removeChild(b);b=null;a()};w.documentElement.appendChild(b)}:function(a){setTimeout(a,0)};return{scheduler:d,
yb:function(b){f||a.ma.scheduler(c);e[f++]=b;return g++},cancel:function(a){a-=g-f;a>=l&&a<f&&(e[a]=null)},resetForTesting:function(){var a=f-l;l=f=e.length=0;return a},Rd:b}}();a.b("tasks",a.ma);a.b("tasks.schedule",a.ma.yb);a.b("tasks.runEarly",a.ma.Rd);a.Ta={throttle:function(b,c){b.throttleEvaluation=c;var d=null;return a.$({read:b,write:function(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},c)}})},rateLimit:function(a,c){var b,e;"number"==typeof c?b=c:(b=c.timeout,e=c.method);a.Hb=!1;
var f="function"==typeof e?e:"notifyWhenChangesStop"==e?Z:Y;a.tb(function(a){return f(a,b,c)})},deferred:function(b,c){if(!0!==c)throw Error("The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.");b.Hb||(b.Hb=!0,b.tb(function(c){var d,f=!1;return function(){if(!f){a.ma.cancel(d);d=a.ma.yb(c);try{f=!0,b.notifySubscribers(q,"dirty")}finally{f=!1}}}}))},notify:function(a,c){a.equalityComparer="always"==c?null:J}};var X={undefined:1,"boolean":1,
number:1,string:1};a.b("extenders",a.Ta);a.gc=function(b,c,d){this.da=b;this.kc=c;this.lc=d;this.Ib=!1;this.ab=this.Jb=null;a.J(this,"dispose",this.s);a.J(this,"disposeWhenNodeIsRemoved",this.l)};a.gc.prototype.s=function(){this.Ib||(this.ab&&a.a.I.xb(this.Jb,this.ab),this.Ib=!0,this.lc(),this.da=this.kc=this.lc=this.Jb=this.ab=null)};a.gc.prototype.l=function(b){this.Jb=b;a.a.I.za(b,this.ab=this.s.bind(this))};a.R=function(){a.a.zb(this,C);C.ob(this)};var C={ob:function(a){a.S={change:[]};a.rc=1},
subscribe:function(b,c,d){var e=this;d=d||"change";var f=new a.gc(e,c?b.bind(c):b,function(){a.a.hb(e.S[d],f);e.cb&&e.cb(d)});e.Qa&&e.Qa(d);e.S[d]||(e.S[d]=[]);e.S[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";"change"===c&&this.Gb();if(this.Wa(c)){c="change"===c&&this.dd||this.S[c].slice(0);try{a.v.wc();for(var d=0,e;e=c[d];++d)e.Ib||e.kc(b)}finally{a.v.end()}}},mb:function(){return this.rc},Cd:function(a){return this.mb()!==a},Gb:function(){++this.rc},tb:function(b){var c=this,
d=a.N(c),e,f,g,l,m;c.bb||(c.bb=c.notifySubscribers,c.notifySubscribers=aa);var k=b(function(){c.Ka=!1;d&&l===c&&(l=c.mc?c.mc():c());var a=f||m&&c.qb(g,l);m=f=e=!1;a&&c.bb(g=l)});c.pc=function(a,b){b&&c.Ka||(m=!b);c.dd=c.S.change.slice(0);c.Ka=e=!0;l=a;k()};c.oc=function(a){e||(g=a,c.bb(a,"beforeChange"))};c.qc=function(){m=!0};c.fd=function(){c.qb(g,c.w(!0))&&(f=!0)}},Wa:function(a){return this.S[a]&&this.S[a].length},Ad:function(b){if(b)return this.S[b]&&this.S[b].length||0;var c=0;a.a.O(this.S,
function(a,b){"dirty"!==a&&(c+=b.length)});return c},qb:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},toString:function(){return"[object Object]"},extend:function(b){var c=this;b&&a.a.O(b,function(b,e){b=a.Ta[b];"function"==typeof b&&(c=b(c,e)||c)});return c}};a.J(C,"init",C.ob);a.J(C,"subscribe",C.subscribe);a.J(C,"extend",C.extend);a.J(C,"getSubscriptionsCount",C.Ad);a.a.Ba&&a.a.setPrototypeOf(C,Function.prototype);a.R.fn=C;a.Pc=function(a){return null!=a&&"function"==
typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.R);a.b("isSubscribable",a.Pc);a.U=a.v=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{wc:b,end:c,ac:function(b){if(e){if(!a.Pc(b))throw Error("Only subscribable things can act as dependencies");e.nd.call(e.od,b,b.ed||(b.ed=++f))}},K:function(a,d,e){try{return b(),a.apply(d,e||[])}finally{c()}},pa:function(){if(e)return e.o.pa()},Va:function(){if(e)return e.o.Va()},rb:function(){if(e)return e.rb},
o:function(){if(e)return e.o}}}();a.b("computedContext",a.U);a.b("computedContext.getDependenciesCount",a.U.pa);a.b("computedContext.getDependencies",a.U.Va);a.b("computedContext.isInitial",a.U.rb);a.b("computedContext.registerDependency",a.U.ac);a.b("ignoreDependencies",a.Wd=a.v.K);var H=a.a.Da("_latestValue");a.sa=function(b){function c(){if(0<arguments.length)return c.qb(c[H],arguments[0])&&(c.xa(),c[H]=arguments[0],c.wa()),this;a.v.ac(c);return c[H]}c[H]=b;a.a.Ba||a.a.extend(c,a.R.fn);a.R.fn.ob(c);
a.a.zb(c,E);a.options.deferUpdates&&a.Ta.deferred(c,!0);return c};var E={equalityComparer:J,w:function(){return this[H]},wa:function(){this.notifySubscribers(this[H],"spectate");this.notifySubscribers(this[H])},xa:function(){this.notifySubscribers(this[H],"beforeChange")}};a.a.Ba&&a.a.setPrototypeOf(E,a.R.fn);var I=a.sa.Na="__ko_proto__";E[I]=a.sa;a.N=function(b){if((b="function"==typeof b&&b[I])&&b!==E[I]&&b!==a.o.fn[I])throw Error("Invalid object that looks like an observable; possibly from another Knockout instance");
return!!b};a.Ya=function(b){return"function"==typeof b&&(b[I]===E[I]||b[I]===a.o.fn[I]&&b.Mc)};a.b("observable",a.sa);a.b("isObservable",a.N);a.b("isWriteableObservable",a.Ya);a.b("isWritableObservable",a.Ya);a.b("observable.fn",E);a.J(E,"peek",E.w);a.J(E,"valueHasMutated",E.wa);a.J(E,"valueWillMutate",E.xa);a.Ia=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.sa(b);a.a.zb(b,
a.Ia.fn);return b.extend({trackArrayChanges:!0})};a.Ia.fn={remove:function(b){for(var c=this.w(),d=[],e="function"!=typeof b||a.N(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var g=c[f];if(e(g)){0===d.length&&this.xa();if(c[f]!==g)throw Error("Array modified during remove; cannot remove item");d.push(g);c.splice(f,1);f--}}d.length&&this.wa();return d},removeAll:function(b){if(b===q){var c=this.w(),d=c.slice(0);this.xa();c.splice(0,c.length);this.wa();return d}return b?this.remove(function(c){return 0<=
a.a.A(b,c)}):[]},destroy:function(b){var c=this.w(),d="function"!=typeof b||a.N(b)?function(a){return a===b}:b;this.xa();for(var e=c.length-1;0<=e;e--){var f=c[e];d(f)&&(f._destroy=!0)}this.wa()},destroyAll:function(b){return b===q?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.a.A(b,c)}):[]},indexOf:function(b){var c=this();return a.a.A(c,b)},replace:function(a,c){a=this.indexOf(a);0<=a&&(this.xa(),this.w()[a]=c,this.wa())},sorted:function(a){var b=this().slice(0);return a?
b.sort(a):b.sort()},reversed:function(){return this().slice(0).reverse()}};a.a.Ba&&a.a.setPrototypeOf(a.Ia.fn,a.sa.fn);a.a.C("pop push reverse shift sort splice unshift".split(" "),function(b){a.Ia.fn[b]=function(){var a=this.w();this.xa();this.yc(a,b,arguments);var d=a[b].apply(a,arguments);this.wa();return d===a?this:d}});a.a.C(["slice"],function(b){a.Ia.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.Oc=function(b){return a.N(b)&&"function"==typeof b.remove&&"function"==typeof b.push};
a.b("observableArray",a.Ia);a.b("isObservableArray",a.Oc);a.Ta.trackArrayChanges=function(b,c){function d(){function c(){if(l){var c=[].concat(b.w()||[]);if(b.Wa("arrayChange")){if(!f||1<l)f=a.a.Ob(m,c,b.Nb);var d=f}m=c;f=null;l=0;d&&d.length&&b.notifySubscribers(d,"arrayChange")}}e?c():(e=!0,k=b.notifySubscribers,b.notifySubscribers=function(a,b){b&&"change"!==b||++l;return k.apply(this,arguments)},m=[].concat(b.w()||[]),f=null,g=b.subscribe(c))}b.Nb={};c&&"object"==typeof c&&a.a.extend(b.Nb,c);
b.Nb.sparse=!0;if(!b.yc){var e=!1,f=null,g,l=0,m,k,h=b.Qa,n=b.cb;b.Qa=function(a){h&&h.call(b,a);"arrayChange"===a&&d()};b.cb=function(a){n&&n.call(b,a);"arrayChange"!==a||b.Wa("arrayChange")||(k&&(b.notifySubscribers=k,k=q),g&&g.s(),g=null,e=!1,m=q)};b.yc=function(b,c,d){function h(a,b,c){return k[k.length]={status:a,value:b,index:c}}if(e&&!l){var k=[],n=b.length,g=d.length,p=0;switch(c){case "push":p=n;case "unshift":for(c=0;c<g;c++)h("added",d[c],p+c);break;case "pop":p=n-1;case "shift":n&&h("deleted",
b[p],p);break;case "splice":c=Math.min(Math.max(0,0>d[0]?n+d[0]:d[0]),n);n=1===g?n:Math.min(c+(d[1]||0),n);g=c+g-2;p=Math.max(n,g);for(var m=[],r=[],v=2;c<p;++c,++v)c<n&&r.push(h("deleted",b[c],c)),c<g&&m.push(h("added",d[v],c));a.a.Jc(r,m);break;default:return}f=k}}}};var t=a.a.Da("_state");a.o=a.$=function(b,c,d){function e(){if(0<arguments.length){if("function"===typeof f)f.apply(g.lb,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");
return this}g.qa||a.v.ac(e);(g.ka||g.G&&e.Xa())&&e.ha();return g.X}"object"===typeof b?d=b:(d=d||{},b&&(d.read=b));if("function"!=typeof d.read)throw Error("Pass a function that returns the value of the ko.computed");var f=d.write,g={X:q,ra:!0,ka:!0,pb:!1,hc:!1,qa:!1,vb:!1,G:!1,Vc:d.read,lb:c||d.owner,l:d.disposeWhenNodeIsRemoved||d.l||null,Sa:d.disposeWhen||d.Sa,Qb:null,F:{},V:0,Hc:null};e[t]=g;e.Mc="function"===typeof f;a.a.Ba||a.a.extend(e,a.R.fn);a.R.fn.ob(e);a.a.zb(e,A);d.pure?(g.vb=!0,g.G=!0,
a.a.extend(e,da)):d.deferEvaluation&&a.a.extend(e,ea);a.options.deferUpdates&&a.Ta.deferred(e,!0);g.l&&(g.hc=!0,g.l.nodeType||(g.l=null));g.G||d.deferEvaluation||e.ha();g.l&&e.ja()&&a.a.I.za(g.l,g.Qb=function(){e.s()});return e};var A={equalityComparer:J,pa:function(){return this[t].V},Va:function(){var b=[];a.a.O(this[t].F,function(a,d){b[d.La]=d.da});return b},Ub:function(b){if(!this[t].V)return!1;var c=this.Va();return-1!==a.a.A(c,b)?!0:!!a.a.Lb(c,function(a){return a.Ub&&a.Ub(b)})},tc:function(a,
c,d){if(this[t].vb&&c===this)throw Error("A 'pure' computed must not be called recursively");this[t].F[a]=d;d.La=this[t].V++;d.Ma=c.mb()},Xa:function(){var a,c,d=this[t].F;for(a in d)if(Object.prototype.hasOwnProperty.call(d,a)&&(c=d[a],this.Ja&&c.da.Ka||c.da.Cd(c.Ma)))return!0},Id:function(){this.Ja&&!this[t].pb&&this.Ja(!1)},ja:function(){var a=this[t];return a.ka||0<a.V},Qd:function(){this.Ka?this[t].ka&&(this[t].ra=!0):this.Gc()},Zc:function(a){if(a.Hb){var b=a.subscribe(this.Id,this,"dirty"),
d=a.subscribe(this.Qd,this);return{da:a,s:function(){b.s();d.s()}}}return a.subscribe(this.Gc,this)},Gc:function(){var b=this,c=b.throttleEvaluation;c&&0<=c?(clearTimeout(this[t].Hc),this[t].Hc=a.a.setTimeout(function(){b.ha(!0)},c)):b.Ja?b.Ja(!0):b.ha(!0)},ha:function(b){var c=this[t],d=c.Sa,e=!1;if(!c.pb&&!c.qa){if(c.l&&!a.a.Rb(c.l)||d&&d()){if(!c.hc){this.s();return}}else c.hc=!1;c.pb=!0;try{e=this.yd(b)}finally{c.pb=!1}return e}},yd:function(b){var c=this[t],d=c.vb?q:!c.V;var e={pd:this,kb:c.F,
Pb:c.V};a.v.wc({od:e,nd:ca,o:this,rb:d});c.F={};c.V=0;var f=this.xd(c,e);c.V?e=this.qb(c.X,f):(this.s(),e=!0);e&&(c.G?this.Gb():this.notifySubscribers(c.X,"beforeChange"),c.X=f,this.notifySubscribers(c.X,"spectate"),!c.G&&b&&this.notifySubscribers(c.X),this.qc&&this.qc());d&&this.notifySubscribers(c.X,"awake");return e},xd:function(b,c){try{var d=b.Vc;return b.lb?d.call(b.lb):d()}finally{a.v.end(),c.Pb&&!b.G&&a.a.O(c.kb,ba),b.ra=b.ka=!1}},w:function(a){var b=this[t];(b.ka&&(a||!b.V)||b.G&&this.Xa())&&
this.ha();return b.X},tb:function(b){a.R.fn.tb.call(this,b);this.mc=function(){this[t].G||(this[t].ra?this.ha():this[t].ka=!1);return this[t].X};this.Ja=function(a){this.oc(this[t].X);this[t].ka=!0;a&&(this[t].ra=!0);this.pc(this,!a)}},s:function(){var b=this[t];!b.G&&b.F&&a.a.O(b.F,function(a,b){b.s&&b.s()});b.l&&b.Qb&&a.a.I.xb(b.l,b.Qb);b.F=q;b.V=0;b.qa=!0;b.ra=!1;b.ka=!1;b.G=!1;b.l=q;b.Sa=q;b.Vc=q;this.Mc||(b.lb=q)}},da={Qa:function(b){var c=this,d=c[t];if(!d.qa&&d.G&&"change"==b){d.G=!1;if(d.ra||
c.Xa())d.F=null,d.V=0,c.ha()&&c.Gb();else{var e=[];a.a.O(d.F,function(a,b){e[b.La]=a});a.a.C(e,function(a,b){var e=d.F[a],f=c.Zc(e.da);f.La=b;f.Ma=e.Ma;d.F[a]=f});c.Xa()&&c.ha()&&c.Gb()}d.qa||c.notifySubscribers(d.X,"awake")}},cb:function(b){var c=this[t];c.qa||"change"!=b||this.Wa("change")||(a.a.O(c.F,function(a,b){b.s&&(c.F[a]={da:b.da,La:b.La,Ma:b.Ma},b.s())}),c.G=!0,this.notifySubscribers(q,"asleep"))},mb:function(){var b=this[t];b.G&&(b.ra||this.Xa())&&this.ha();return a.R.fn.mb.call(this)}},
ea={Qa:function(a){"change"!=a&&"beforeChange"!=a||this.w()}};a.a.Ba&&a.a.setPrototypeOf(A,a.R.fn);var K=a.sa.Na;A[K]=a.o;a.Nc=function(a){return"function"==typeof a&&a[K]===A[K]};a.Ed=function(b){return a.Nc(b)&&b[t]&&b[t].vb};a.b("computed",a.o);a.b("dependentObservable",a.o);a.b("isComputed",a.Nc);a.b("isPureComputed",a.Ed);a.b("computed.fn",A);a.J(A,"peek",A.w);a.J(A,"dispose",A.s);a.J(A,"isActive",A.ja);a.J(A,"getDependenciesCount",A.pa);a.J(A,"getDependencies",A.Va);a.wb=function(b,c){if("function"===
typeof b)return a.o(b,c,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.o(b,c)};a.b("pureComputed",a.wb);(function(){function b(a,f,g){g=g||new d;a=f(a);if("object"!=typeof a||null===a||a===q||a instanceof RegExp||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var e=a instanceof Array?[]:{};g.save(a,e);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":e[c]=d;break;case "object":case "undefined":var h=
g.get(d);e[c]=h!==q?h:b(d,f,g)}});return e}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.$c=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.N(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.$c(b);return a.a.fc(b,c,d)};d.prototype={constructor:d,save:function(b,
c){var d=a.a.A(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),this.values.push(c))},get:function(b){b=a.a.A(this.keys,b);return 0<=b?this.values[b]:q}}})();a.b("toJS",a.$c);a.b("toJSON",a.toJSON);a.Vd=function(b,c,d){function e(c){var e=a.wb(b,d).extend({Ga:"always"}),f=e.subscribe(function(a){a&&(f.s(),c(a))});e.notifySubscribers(e.w());return f}return"function"!==typeof Promise||c?e(c.bind(d)):new Promise(e)};a.b("when",a.Vd);(function(){a.u={L:function(b){switch(a.a.P(b)){case "option":return!0===
b.__ko__hasDomDataOptionValue__?a.a.g.get(b,a.f.options.Yb):7>=a.a.W?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.u.L(b.options[b.selectedIndex]):q;default:return b.value}},ya:function(b,c,d){switch(a.a.P(b)){case "option":"string"===typeof c?(a.a.g.set(b,a.f.options.Yb,q),"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__,b.value=c):(a.a.g.set(b,a.f.options.Yb,c),b.__ko__hasDomDataOptionValue__=
!0,b.value="number"===typeof c?c:"");break;case "select":if(""===c||null===c)c=q;for(var e=-1,f=0,g=b.options.length,l;f<g;++f)if(l=a.u.L(b.options[f]),l==c||""===l&&c===q){e=f;break}if(d||0<=e||c===q&&1<b.size)b.selectedIndex=e,6===a.a.W&&a.a.setTimeout(function(){b.selectedIndex=e},0);break;default:if(null===c||c===q)c="";b.value=c}}}})();a.b("selectExtensions",a.u);a.b("selectExtensions.readValue",a.u.L);a.b("selectExtensions.writeValue",a.u.ya);a.m=function(){function b(b){b=a.a.Cb(b);123===b.charCodeAt(0)&&
(b=b.slice(1,-1));b+="\n,";var c=[],d=b.match(e),n=[],p=0;if(1<d.length){for(var l=0,m;m=d[l];++l){var z=m.charCodeAt(0);if(44===z){if(0>=p){c.push(D&&n.length?{key:D,value:n.join("")}:{unknown:D||n.join("")});var D=p=0;n=[];continue}}else if(58===z){if(!p&&!D&&1===n.length){D=n.pop();continue}}else if(47===z&&1<m.length&&(47===m.charCodeAt(1)||42===m.charCodeAt(1)))continue;else 47===z&&l&&1<m.length?(z=d[l-1].match(f))&&!g[z[0]]&&(b=b.substr(b.indexOf(m)+1),d=b.match(e),l=-1,m="/"):40===z||123===
z||91===z?++p:41===z||125===z||93===z?--p:D||n.length||34!==z&&39!==z||(m=m.slice(1,-1));n.push(m)}if(0<p)throw Error("Unbalanced parentheses, braces, or brackets");}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=/"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|`(?:\\.|[^`])*`|\/\*(?:[^*]|\*+[^*/])*\*+\/|\/\/.*\n|\/(?:\\.|[^/])+\/w*|[^\s:,/][^,"'`{}()/:[\]]*[^\s,"'`{}()/:[\]]|[^\s]/g,f=/[\])"'A-Za-z0-9_$]+$/,g={"in":1,"return":1,"typeof":1},l={};return{Ra:[],
va:l,Zb:b,ub:function(e,f){function h(b,e){if(!m){var f=a.getBindingHandler(b);if(f&&f.preprocess&&!(e=f.preprocess(e,b,h)))return;if(f=l[b]){var p=e;0<=a.a.A(c,p)?p=!1:(f=p.match(d),p=null===f?!1:f[1]?"Object("+f[1]+")"+f[2]:p);f=p}f&&k.push("'"+("string"==typeof l[b]?l[b]:b)+"':function(_z){"+p+"=_z}")}g&&(e="function(){return "+e+" }");n.push("'"+b+"':"+e)}f=f||{};var n=[],k=[],g=f.valueAccessors,m=f.bindingParams;e="string"===typeof e?b(e):e;a.a.C(e,function(a){h(a.key||a.unknown,a.value)});k.length&&
h("_ko_property_writers","{"+k.join(",")+" }");return n.join(",")},Hd:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},$a:function(b,c,d,e,f){if(b&&a.N(b))!a.Ya(b)||f&&b.w()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.m);a.b("expressionRewriting.bindingRewriteValidators",a.m.Ra);a.b("expressionRewriting.parseObjectLiteral",a.m.Zb);a.b("expressionRewriting.preProcessBindings",a.m.ub);a.b("expressionRewriting._twoWayBindings",
a.m.va);a.b("jsonExpressionRewriting",a.m);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.m.ub);(function(){function b(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&l.test(f?a.text:a.nodeValue)}function d(d,e){for(var h=d,f=1,n=[];h=h.nextSibling;){if(c(h)&&(a.a.g.set(h,k,!0),f--,0===f))return n;n.push(h);b(h)&&f++}if(!e)throw Error("Cannot find closing comment tag to match: "+d.nodeValue);return null}function e(a,b){return(b=d(a,b))?0<
b.length?b[b.length-1].nextSibling:a.nextSibling:null}var f=w&&"\x3c!--test--\x3e"===w.createComment("test").text,g=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,l=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,m={ul:!0,ol:!0},k="__ko_matchedEndComment__";a.h={ea:{},childNodes:function(a){return b(a)?d(a):a.childNodes},Ea:function(c){if(b(c)){c=a.h.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Sb(c)},ua:function(c,d){if(b(c)){a.h.Ea(c);c=c.nextSibling;
for(var e=0,h=d.length;e<h;e++)c.parentNode.insertBefore(d[e],c)}else a.a.ua(c,d)},Uc:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},Vb:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.h.Uc(c,d)},firstChild:function(a){if(b(a))return!a.nextSibling||c(a.nextSibling)?null:a.nextSibling;if(a.firstChild&&c(a.firstChild))throw Error("Found invalid end comment, as the first child of "+
a);return a.firstChild},nextSibling:function(d){b(d)&&(d=e(d));if(d.nextSibling&&c(d.nextSibling)){var f=d.nextSibling;if(c(f)&&!a.a.g.get(f,k))throw Error("Found end comment without a matching opening comment, as child of "+d);return null}return d.nextSibling},Bd:b,Ud:function(a){return(a=(f?a.text:a.nodeValue).match(g))?a[1]:null},Rc:function(d){if(m[a.a.P(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var h=f.firstChild;var k=null;if(h){do if(k)k.push(h);else if(b(h)){var g=e(h,!0);g?h=g:
k=[h]}else c(h)&&(k=[h]);while(h=h.nextSibling)}if(h=k)for(k=f.nextSibling,g=0;g<h.length;g++)k?d.insertBefore(h[g],k):d.appendChild(h[g])}while(f=f.nextSibling)}}}}})();a.b("virtualElements",a.h);a.b("virtualElements.allowedBindings",a.h.ea);a.b("virtualElements.emptyNode",a.h.Ea);a.b("virtualElements.insertAfter",a.h.Vb);a.b("virtualElements.prepend",a.h.Uc);a.b("virtualElements.setDomNodeChildren",a.h.ua);(function(){a.ga=function(){this.md={}};a.a.extend(a.ga.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=
b.getAttribute("data-bind")||a.i.getComponentNameForNode(b);case 8:return a.h.Bd(b);default:return!1}},getBindings:function(b,c){var d=this.getBindingsString(b,c);d=d?this.parseBindingsString(d,c,b):null;return a.i.sc(d,b,c,!1)},getBindingAccessors:function(b,c){var d=this.getBindingsString(b,c);d=d?this.parseBindingsString(d,c,b,{valueAccessors:!0}):null;return a.i.sc(d,b,c,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.h.Ud(b);default:return null}},
parseBindingsString:function(b,c,d,e){try{var f=this.md,g=b+(e&&e.valueAccessors||""),l;if(!(l=f[g])){var m="with($context){with($data||{}){return{"+a.m.ub(b,e)+"}}}";var k=new Function("$context","$element",m);l=f[g]=k}return l(c,d)}catch(h){throw h.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+h.message,h;}}});a.ga.instance=new a.ga})();a.b("bindingProvider",a.ga);(function(){function b(b){var c=(b=a.a.g.get(b,G))&&b.M;c&&(b.M=null,c.Sc())}function c(c,d,e){this.node=c;this.xc=
d;this.ib=[];this.T=!1;d.M||a.a.I.za(c,b);e&&e.M&&(e.M.ib.push(c),this.Kb=e)}function d(a){return function(){return a}}function e(a){return a()}function f(b){return a.a.Ha(a.v.K(b),function(a,c){return function(){return b()[c]}})}function g(b,c,e){return"function"===typeof b?f(b.bind(null,c,e)):a.a.Ha(b,d)}function l(a,b){return f(this.getBindings.bind(this,a,b))}function m(b,c){var d=a.h.firstChild(c);if(d){var e,f=a.ga.instance,h=f.preprocessNode;if(h){for(;e=d;)d=a.h.nextSibling(e),h.call(f,e);
d=a.h.firstChild(c)}for(;e=d;)d=a.h.nextSibling(e),k(b,e)}a.j.Ga(c,a.j.T)}function k(b,c){var d=b,e=1===c.nodeType;e&&a.h.Rc(c);if(e||a.ga.instance.nodeHasBindings(c))d=n(c,null,b).bindingContextForDescendants;d&&!D[a.a.P(c)]&&m(d,c)}function h(b){var c=[],d={},e=[];a.a.O(b,function B(f){if(!d[f]){var h=a.getBindingHandler(f);h&&(h.after&&(e.push(f),a.a.C(h.after,function(c){if(b[c]){if(-1!==a.a.A(e,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+e.join(", "));
B(c)}}),e.length--),c.push({key:f,Lc:h}));d[f]=!0}});return c}function n(b,c,d){var f=a.a.g.Tb(b,G,{}),k=f.gd;if(!c){if(k)throw Error("You cannot apply bindings multiple times to the same element.");f.gd=!0}k||(f.context=d);if(c&&"function"!==typeof c)var g=c;else{var n=a.ga.instance,p=n.getBindingAccessors||l,m=a.$(function(){if(g=c?c(d,b):p.call(n,b,d)){if(d[r])d[r]();if(d[z])d[z]()}return g},null,{l:b});g&&m.ja()||(m=null)}var v=d,N;if(g){var D=function(){return a.a.Ha(m?m():g,e)},Q=m?function(a){return function(){return(0,m()[a])()}}:
function(a){return g[a]};D.get=function(a){return g[a]&&Q(a)()};D.has=function(a){return a in g};a.j.T in g&&a.j.subscribe(b,a.j.T,function(){var c=(0,g[a.j.T])();if(c){var d=a.h.childNodes(b);d.length&&c(d,a.Dc(d[0]))}});a.j.oa in g&&(v=a.j.Bb(b,d),a.j.subscribe(b,a.j.oa,function(){var c=(0,g[a.j.oa])();c&&a.h.firstChild(b)&&c(b)}));f=h(g);a.a.C(f,function(c){var d=c.Lc.init,e=c.Lc.update,f=c.key;if(8===b.nodeType&&!a.h.ea[f])throw Error("The binding '"+f+"' cannot be used with virtual elements");
try{"function"==typeof d&&a.v.K(function(){var a=d(b,Q(f),D,v.$data,v);if(a&&a.controlsDescendantBindings){if(N!==q)throw Error("Multiple bindings ("+N+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");N=f}}),"function"==typeof e&&a.$(function(){e(b,Q(f),D,v.$data,v)},null,{l:b})}catch(R){throw R.message='Unable to process binding "'+f+": "+g[f]+'"\nMessage: '+R.message,R;}})}f=N===q;return{shouldBindDescendants:f,
bindingContextForDescendants:f&&v}}function p(b,c){return b&&b instanceof a.fa?b:new a.fa(b,q,q,c)}var r=a.a.Da("_subscribable"),v=a.a.Da("_ancestorBindingInfo"),z=a.a.Da("_dataDependency");a.f={};var D={script:!0,textarea:!0,template:!0};a.getBindingHandler=function(b){return a.f[b]};var M={};a.fa=function(b,c,d,e,f){function h(){var b=l?n():n,f=a.a.c(b);c?(a.a.extend(k,c),v in c&&(k[v]=c[v])):(k.$parents=[],k.$root=f,k.ko=a);k[r]=p;g?f=k.$data:(k.$rawData=b,k.$data=f);d&&(k[d]=f);e&&e(k,c,f);if(c&&
c[r]&&!a.U.o().Ub(c[r]))c[r]();m&&(k[z]=m);return k.$data}var k=this,g=b===M,n=g?q:b,l="function"==typeof n&&!a.N(n),p,m=f&&f.dataDependency;f&&f.exportDependencies?h():(p=a.wb(h),p.w(),p.ja()?p.equalityComparer=null:k[r]=q)};a.fa.prototype.createChildContext=function(b,c,d,e){!e&&c&&"object"==typeof c&&(e=c,c=e.as,d=e.extend);if(c&&e&&e.noChildContext){var f="function"==typeof b&&!a.N(b);return new a.fa(M,this,null,function(a){d&&d(a);a[c]=f?b():b},e)}return new a.fa(b,this,c,function(a,b){a.$parentContext=
b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)},e)};a.fa.prototype.extend=function(b,c){return new a.fa(M,this,null,function(c){a.a.extend(c,"function"==typeof b?b(c):b)},c)};var G=a.a.g.Z();c.prototype.Sc=function(){this.Kb&&this.Kb.M&&this.Kb.M.rd(this.node)};c.prototype.rd=function(b){a.a.hb(this.ib,b);!this.ib.length&&this.T&&this.Bc()};c.prototype.Bc=function(){this.T=!0;this.xc.M&&!this.ib.length&&(this.xc.M=null,a.a.I.xb(this.node,b),a.j.Ga(this.node,
a.j.oa),this.Sc())};a.j={T:"childrenComplete",oa:"descendantsComplete",subscribe:function(b,c,d,e){b=a.a.g.Tb(b,G,{});b.Fa||(b.Fa=new a.R);return b.Fa.subscribe(d,e,c)},Ga:function(b,c){var d=a.a.g.get(b,G);if(d&&(d.Fa&&d.Fa.notifySubscribers(b,c),c==a.j.T))if(d.M)d.M.Bc();else if(d.M===q&&d.Fa&&d.Fa.Wa(a.j.oa))throw Error("descendantsComplete event not supported for bindings on this node");},Bb:function(b,d){var e=a.a.g.Tb(b,G,{});e.M||(e.M=new c(b,e,d[v]));return d[v]==e?d:d.extend(function(a){a[v]=
e})}};a.Sd=function(b){return(b=a.a.g.get(b,G))&&b.context};a.eb=function(b,c,d){1===b.nodeType&&a.h.Rc(b);return n(b,c,p(d))};a.kd=function(b,c,d){d=p(d);return a.eb(b,g(c,d,b),d)};a.Pa=function(a,b){1!==b.nodeType&&8!==b.nodeType||m(p(a),b)};a.uc=function(a,b,c){!u&&y.jQuery&&(u=y.jQuery);if(2>arguments.length){if(b=w.body,!b)throw Error("ko.applyBindings: could not find document.body; has the document been loaded?");}else if(!b||1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");
k(p(a,c),b)};a.Cc=function(b){return!b||1!==b.nodeType&&8!==b.nodeType?q:a.Sd(b)};a.Dc=function(b){return(b=a.Cc(b))?b.$data:q};a.b("bindingHandlers",a.f);a.b("bindingEvent",a.j);a.b("bindingEvent.subscribe",a.j.subscribe);a.b("bindingEvent.startPossiblyAsyncContentBinding",a.j.Bb);a.b("applyBindings",a.uc);a.b("applyBindingsToDescendants",a.Pa);a.b("applyBindingAccessorsToNode",a.eb);a.b("applyBindingsToNode",a.kd);a.b("contextFor",a.Cc);a.b("dataFor",a.Dc)})();(function(b){function c(c,e){var k=
Object.prototype.hasOwnProperty.call(f,c)?f[c]:b,h;k?k.subscribe(e):(k=f[c]=new a.R,k.subscribe(e),d(c,function(b,d){d=!(!d||!d.synchronous);g[c]={definition:b,Fd:d};delete f[c];h||d?k.notifySubscribers(b):a.ma.yb(function(){k.notifySubscribers(b)})}),h=!0)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,c)}):b(null,null)})}function e(c,d,f,h){h||(h=a.i.loaders.slice(0));var k=h.shift();if(k){var g=k[c];if(g){var l=!1;if(g.apply(k,d.concat(function(a){l?f(null):
null!==a?f(a):e(c,d,f,h)}))!==b&&(l=!0,!k.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,h)}else f(null)}var f={},g={};a.i={get:function(d,e){var f=Object.prototype.hasOwnProperty.call(g,d)?g[d]:b;f?f.Fd?a.v.K(function(){e(f.definition)}):a.ma.yb(function(){e(f.definition)}):c(d,e)},Ac:function(a){delete g[a]},nc:e};a.i.loaders=[];a.b("components",a.i);a.b("components.get",a.i.get);a.b("components.clearCachedDefinition",
a.i.Ac)})();(function(){function b(b,c,d,e){function h(){0===--g&&e(k)}var k={},g=2,n=d.template;d=d.viewModel;n?f(c,n,function(c){a.i.nc("loadTemplate",[b,c],function(a){k.template=a;h()})}):h();d?f(c,d,function(c){a.i.nc("loadViewModel",[b,c],function(a){k[m]=a;h()})}):h()}function c(a,b,d){if("function"===typeof b)d(function(a){return new b(a)});else if("function"===typeof b[m])d(b[m]);else if("instance"in b){var e=b.instance;d(function(){return e})}else"viewModel"in b?c(a,b.viewModel,d):a("Unknown viewModel value: "+
b)}function d(b){switch(a.a.P(b)){case "script":return a.a.ta(b.text);case "textarea":return a.a.ta(b.value);case "template":if(e(b.content))return a.a.Ca(b.content.childNodes)}return a.a.Ca(b.childNodes)}function e(a){return y.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function f(a,b,c){"string"===typeof b.require?V||y.require?(V||y.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function g(a){return function(b){throw Error("Component '"+a+"': "+
b);}}var l={};a.i.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.i.sb(b))throw Error("Component "+b+" is already registered");l[b]=c};a.i.sb=function(a){return Object.prototype.hasOwnProperty.call(l,a)};a.i.unregister=function(b){delete l[b];a.i.Ac(b)};a.i.Ec={getConfig:function(b,c){c(a.i.sb(b)?l[b]:null)},loadComponent:function(a,c,d){var e=g(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,c,f){b=g(b);if("string"===typeof c)f(a.a.ta(c));else if(c instanceof
Array)f(c);else if(e(c))f(a.a.la(c.childNodes));else if(c.element)if(c=c.element,y.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)f(d(c));else if("string"===typeof c){var h=w.getElementById(c);h?f(d(h)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,d){c(g(a),b,d)}};var m="createViewModel";a.b("components.register",a.i.register);a.b("components.isRegistered",a.i.sb);a.b("components.unregister",
a.i.unregister);a.b("components.defaultLoader",a.i.Ec);a.i.loaders.push(a.i.Ec);a.i.cd=l})();(function(){function b(b,e){var d=b.getAttribute("params");return d?(d=c.parseBindingsString(d,e,b,{valueAccessors:!0,bindingParams:!0}),d=a.a.Ha(d,function(c){return a.o(c,null,{l:b})}),e=a.a.Ha(d,function(c){var d=c.w();return c.ja()?a.o({read:function(){return a.a.c(c())},write:a.Ya(d)&&function(a){c()(a)},l:b}):d}),Object.prototype.hasOwnProperty.call(e,"$raw")||(e.$raw=d),e):{$raw:{}}}a.i.getComponentNameForNode=
function(b){var c=a.a.P(b);if(a.i.sb(c)&&(-1!=c.indexOf("-")||"[object HTMLUnknownElement]"==""+b||8>=a.a.W&&b.tagName===c))return c};a.i.sc=function(c,e,f,g){if(1===e.nodeType){var d=a.i.getComponentNameForNode(e);if(d){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var m={name:d,params:b(e,f)};c.component=g?function(){return m}:m}}return c};var c=new a.ga;9>a.a.W&&(a.i.register=function(a){return function(b){return a.apply(this,
arguments)}}(a.i.register),w.createDocumentFragment=function(b){return function(){var c=b(),d=a.i.cd,g;for(g in d);return c}}(w.createDocumentFragment))})();(function(){function b(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.Ca(c);a.h.ua(d,b)}function c(a,b,c){var d=a.createViewModel;return d?d.call(a,b,c):b}var d=0;a.f.component={init:function(e,f,g,l,m){function k(){var a=h&&h.dispose;"function"===typeof a&&a.call(h);p&&p.s();n=h=p=null}var h,n,p,r=a.a.la(a.h.childNodes(e));
a.h.Ea(e);a.a.I.za(e,k);a.o(function(){var g=a.a.c(f()),l,D;"string"===typeof g?l=g:(l=a.a.c(g.name),D=a.a.c(g.params));if(!l)throw Error("No component name specified");var q=a.j.Bb(e,m),G=n=++d;a.i.get(l,function(d){if(n===G){k();if(!d)throw Error("Unknown component '"+l+"'");b(l,d,e);var f=c(d,D,{element:e,templateNodes:r});d=q.createChildContext(f,{extend:function(a){a.$component=f;a.$componentTemplateNodes=r}});f&&f.koDescendantsComplete&&(p=a.j.subscribe(e,a.j.oa,f.koDescendantsComplete,f));
h=f;a.Pa(d,e)}})},null,{l:e});return{controlsDescendantBindings:!0}}};a.h.ea.component=!0})();var W={"class":"className","for":"htmlFor"};a.f.attr={update:function(b,c){c=a.a.c(c())||{};a.a.O(c,function(c,e){e=a.a.c(e);var d=c.indexOf(":");d="lookupNamespaceURI"in b&&0<d&&b.lookupNamespaceURI(c.substr(0,d));var g=!1===e||null===e||e===q;g?d?b.removeAttributeNS(d,c):b.removeAttribute(c):e=e.toString();8>=a.a.W&&c in W?(c=W[c],g?b.removeAttribute(c):b[c]=e):g||(d?b.setAttributeNS(d,c,e):b.setAttribute(c,
e));"name"===c&&a.a.Xc(b,g?"":e)})}};(function(){a.f.checked={after:["value","attr"],init:function(b,c,d){function e(){var e=b.checked,f=g();if(!a.U.rb()&&(e||!m&&!a.U.pa())){var k=a.v.K(c);if(h){var p=n?k.w():k,G=r;r=f;G!==f?e&&(a.a.Oa(p,f,!0),a.a.Oa(p,G,!1)):a.a.Oa(p,f,e);n&&a.Ya(k)&&k(p)}else l&&(f===q?f=e:e||(f=q)),a.m.$a(k,d,"checked",f,!0)}}function f(){var d=a.a.c(c()),e=g();h?(b.checked=0<=a.a.A(d,e),r=e):b.checked=l&&e===q?!!d:g()===d}var g=a.wb(function(){if(d.has("checkedValue"))return a.a.c(d.get("checkedValue"));
if(p)return d.has("value")?a.a.c(d.get("value")):b.value}),l="checkbox"==b.type,m="radio"==b.type;if(l||m){var k=c(),h=l&&a.a.c(k)instanceof Array,n=!(h&&k.push&&k.splice),p=m||h,r=h?g():q;m&&!b.name&&a.f.uniqueName.init(b,function(){return!0});a.o(e,null,{l:b});a.a.H(b,"click",e);a.o(f,null,{l:b});k=q}}};a.m.va.checked=!0;a.f.checkedValue={update:function(b,c){b.value=a.a.c(c())}}})();a.f["class"]={update:function(b,c){c=a.a.Cb(a.a.c(c()));a.a.Eb(b,b.__ko__cssValue,!1);b.__ko__cssValue=c;a.a.Eb(b,
c,!0)}};a.f.css={update:function(b,c){var d=a.a.c(c());null!==d&&"object"==typeof d?a.a.O(d,function(c,d){d=a.a.c(d);a.a.Eb(b,c,d)}):a.f["class"].update(b,c)}};a.f.enable={update:function(b,c){(c=a.a.c(c()))&&b.disabled?b.removeAttribute("disabled"):c||b.disabled||(b.disabled=!0)}};a.f.disable={update:function(b,c){a.f.enable.update(b,function(){return!a.a.c(c())})}};a.f.event={init:function(b,c,d,e,f){var g=c()||{};a.a.O(g,function(g){"string"==typeof g&&a.a.H(b,g,function(b){var k=c()[g];if(k){try{var h=
a.a.la(arguments);e=f.$data;h.unshift(e);var n=k.apply(e,h)}finally{!0!==n&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.f.foreach={Qc:function(b){return function(){var c=b(),d=a.a.$b(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.ba.Na};a.a.c(c);return{foreach:d.data,as:d.as,noChildContext:d.noChildContext,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,
afterRender:d.afterRender,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.ba.Na}}},init:function(b,c){return a.f.template.init(b,a.f.foreach.Qc(c))},update:function(b,c,d,e,f){return a.f.template.update(b,a.f.foreach.Qc(c),d,e,f)}};a.m.Ra.foreach=!1;a.h.ea.foreach=!0;a.f.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){try{var g=f.activeElement}catch(h){g=f.body}e=g===b}f=c();a.m.$a(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=
e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),g=e.bind(null,!1);a.a.H(b,"focus",f);a.a.H(b,"focusin",f);a.a.H(b,"blur",g);a.a.H(b,"focusout",g);b.__ko_hasfocusLastValue=!1},update:function(b,c){c=!!a.a.c(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===c||(c?b.focus():b.blur(),!c&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.v.K(a.a.Fb,null,[b,c?"focusin":"focusout"]))}};a.m.va.hasfocus=!0;a.f.hasFocus=a.f.hasfocus;a.m.va.hasFocus="hasfocus";a.f.html={init:function(){return{controlsDescendantBindings:!0}},
update:function(b,c){a.a.dc(b,c())}};(function(){function b(b,d,e){a.f[b]={init:function(b,c,l,m,k){var f,g,p={},r;if(d){m=l.get("as");var v=l.get("noChildContext");var z=!(m&&v);p={as:m,noChildContext:v,exportDependencies:z}}var q=(r="render"==l.get("completeOn"))||l.has(a.j.oa);a.o(function(){var h=a.a.c(c()),n=!e!==!h,l=!g;if(z||n!==f){q&&(k=a.j.Bb(b,k));if(n){if(!d||z)p.dataDependency=a.U.o();var m=d?k.createChildContext("function"==typeof h?h:c,p):a.U.pa()?k.extend(null,p):k}l&&a.U.pa()&&(g=
a.a.Ca(a.h.childNodes(b),!0));n?(l||a.h.ua(b,a.a.Ca(g)),a.Pa(m,b)):(a.h.Ea(b),r||a.j.Ga(b,a.j.T));f=n}},null,{l:b});return{controlsDescendantBindings:!0}}};a.m.Ra[b]=!1;a.h.ea[b]=!0}b("if");b("ifnot",!1,!0);b("with",!0)})();a.f.let={init:function(b,c,d,e,f){c=f.extend(c);a.Pa(c,b);return{controlsDescendantBindings:!0}}};a.h.ea.let=!0;var S={};a.f.options={init:function(b){if("select"!==a.a.P(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},
update:function(b,c,d){function e(){return a.a.fb(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function g(c,e){v&&h?a.u.ya(b,a.a.c(d.get("value")),!0):r.length&&(c=0<=a.a.A(r,a.u.L(e[0])),a.a.Yc(e[0],c),v&&!c&&a.v.K(a.a.Fb,null,[b,"change"]))}var l=b.multiple,m=0!=b.length&&l?b.scrollTop:null,k=a.a.c(c()),h=d.get("valueAllowUnset")&&d.has("value"),n=d.get("optionsIncludeDestroyed");c={};var p,r=[];h||(l?r=a.a.Mb(e(),a.u.L):
0<=b.selectedIndex&&r.push(a.u.L(b.options[b.selectedIndex])));k&&("undefined"==typeof k.length&&(k=[k]),p=a.a.fb(k,function(b){return n||b===q||null===b||!a.a.c(b._destroy)}),d.has("optionsCaption")&&(k=a.a.c(d.get("optionsCaption")),null!==k&&k!==q&&p.unshift(S)));var v=!1;c.beforeRemove=function(a){b.removeChild(a)};k=g;d.has("optionsAfterRender")&&"function"==typeof d.get("optionsAfterRender")&&(k=function(b,c){g(0,c);a.v.K(d.get("optionsAfterRender"),null,[c[0],b!==S?b:q])});a.a.cc(b,p,function(c,
e,g){g.length&&(r=!h&&g[0].selected?[a.u.L(g[0])]:[],v=!0);e=b.ownerDocument.createElement("option");c===S?(a.a.Ab(e,d.get("optionsCaption")),a.u.ya(e,q)):(g=f(c,d.get("optionsValue"),c),a.u.ya(e,a.a.c(g)),c=f(c,d.get("optionsText"),g),a.a.Ab(e,c));return[e]},c,k);a.v.K(function(){if(h)a.u.ya(b,a.a.c(d.get("value")),!0);else{var c;l?c=r.length&&e().length<r.length:c=r.length&&0<=b.selectedIndex?a.u.L(b.options[b.selectedIndex])!==r[0]:r.length||0<=b.selectedIndex;c&&a.a.Fb(b,"change")}});a.a.vd(b);
m&&20<Math.abs(m-b.scrollTop)&&(b.scrollTop=m)}};a.f.options.Yb=a.a.g.Z();a.f.selectedOptions={after:["options","foreach"],init:function(b,c,d){a.a.H(b,"change",function(){var e=c(),f=[];a.a.C(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.u.L(b))});a.m.$a(e,d,"selectedOptions",f)})},update:function(b,c){if("select"!=a.a.P(b))throw Error("values binding applies only to SELECT elements");var d=a.a.c(c());c=b.scrollTop;d&&"number"==typeof d.length&&a.a.C(b.getElementsByTagName("option"),
function(b){var c=0<=a.a.A(d,a.u.L(b));b.selected!=c&&a.a.Yc(b,c)});b.scrollTop=c}};a.m.va.selectedOptions=!0;a.f.style={update:function(b,c){c=a.a.c(c()||{});a.a.O(c,function(c,e){e=a.a.c(e);if(null===e||e===q||!1===e)e="";if(u)u(b).css(c,e);else if(/^--/.test(c))b.style.setProperty(c,e);else{c=c.replace(/-(\w)/g,function(a,b){return b.toUpperCase()});var d=b.style[c];b.style[c]=e;e===d||b.style[c]!=d||isNaN(e)||(b.style[c]=e+"px")}})}};a.f.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");
a.a.H(b,"submit",function(a){var d=c();try{var e=d.call(f.$data,b)}finally{!0!==e&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.f.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Ab(b,c())}};a.h.ea.text=!0;(function(){if(y&&y.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=y.navigator.userAgent,d,e,f,g,l;(d=y.opera&&y.opera.version&&parseInt(y.opera.version()))||(l=b(c.match(/Edge\/([^ ]+)$/)))||b(c.match(/Chrome\/([^ ]+)/))||(e=b(c.match(/Version\/([^ ]+) Safari/)))||
(f=b(c.match(/Firefox\/([^ ]+)/)))||(g=a.a.W||b(c.match(/MSIE ([^ ]+)/)))||(g=b(c.match(/rv:([^ )]+)/)))}if(8<=g&&10>g)var m=a.a.g.Z(),k=a.a.g.Z(),h=function(b){var c=this.activeElement;(c=c&&a.a.g.get(c,k))&&c(b)},n=function(b,c){var d=b.ownerDocument;a.a.g.get(d,m)||(a.a.g.set(d,m,!0),a.a.H(d,"selectionchange",h));a.a.g.set(b,k,c)};a.f.textInput={init:function(b,c,h){function k(c,d){a.a.H(b,c,d)}function p(){var d=a.a.c(c());if(null===d||d===q)d="";u!==q&&d===u?a.a.setTimeout(p,4):b.value!==d&&
(x=!0,b.value=d,x=!1,v=b.value)}function m(){t||(u=b.value,t=a.a.setTimeout(r,4))}function r(){clearTimeout(t);u=t=q;var d=b.value;v!==d&&(v=d,a.m.$a(c(),h,"textInput",d))}var v=b.value,t,u,w=9==a.a.W?m:r,x=!1;g&&k("keypress",r);11>g&&k("propertychange",function(a){x||"value"!==a.propertyName||w(a)});8==g&&(k("keyup",r),k("keydown",r));n&&(n(b,w),k("dragend",m));(!g||9<=g)&&k("input",w);5>e&&"textarea"===a.a.P(b)?(k("keydown",m),k("paste",m),k("cut",m)):11>d?k("keydown",m):4>f?(k("DOMAutoComplete",
r),k("dragdrop",r),k("drop",r)):l&&"number"===b.type&&k("keydown",m);k("change",r);k("blur",r);a.o(p,null,{l:b})}};a.m.va.textInput=!0;a.f.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.f.uniqueName={init:function(b,c){c()&&(c="ko_unique_"+ ++a.f.uniqueName.qd,a.a.Xc(b,c))}};a.f.uniqueName.qd=0;a.f.using={init:function(b,c,d,e,f){var g;d.has("as")&&(g={as:d.get("as"),noChildContext:d.get("noChildContext")});c=f.createChildContext(c,g);a.Pa(c,b);return{controlsDescendantBindings:!0}}};
a.h.ea.using=!0;a.f.value={after:["options","foreach"],init:function(b,c,d){var e=a.a.P(b),f="input"==e;if(!f||"checkbox"!=b.type&&"radio"!=b.type){var g=["change"],l=d.get("valueUpdate"),m=!1,k=null;l&&("string"==typeof l&&(l=[l]),a.a.gb(g,l),g=a.a.vc(g));var h=function(){k=null;m=!1;var e=c(),f=a.u.L(b);a.m.$a(e,d,"value",f)};!a.a.W||!f||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.A(g,"propertychange")||(a.a.H(b,"propertychange",function(){m=!0}),a.a.H(b,"focus",
function(){m=!1}),a.a.H(b,"blur",function(){m&&h()}));a.a.C(g,function(c){var d=h;a.a.Td(c,"after")&&(d=function(){k=a.u.L(b);a.a.setTimeout(h,0)},c=c.substring(5));a.a.H(b,c,d)});var n=f&&"file"==b.type?function(){var d=a.a.c(c());null===d||d===q||""===d?b.value="":a.v.K(h)}:function(){var f=a.a.c(c()),g=a.u.L(b);if(null!==k&&f===k)a.a.setTimeout(n,0);else if(f!==g||g===q)"select"===e?(g=d.get("valueAllowUnset"),a.u.ya(b,f,g),g||f===a.u.L(b)||a.v.K(h)):a.u.ya(b,f)};a.o(n,null,{l:b})}else a.eb(b,
{checkedValue:c})},update:function(){}};a.m.va.value=!0;a.f.visible={update:function(b,c){c=a.a.c(c());var d="none"!=b.style.display;c&&!d?b.style.display="":!c&&d&&(b.style.display="none")}};a.f.hidden={update:function(b,c){a.f.visible.update(b,function(){return!a.a.c(c())})}};(function(b){a.f[b]={init:function(c,d,e,f,g){return a.f.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f,g)}}})("click");a.ca=function(){};a.ca.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");
};a.ca.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.ca.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||w;c=c.getElementById(b);if(!c)throw Error("Cannot find template with ID "+b);return new a.B.D(c)}if(1==b.nodeType||8==b.nodeType)return new a.B.ia(b);throw Error("Unknown template type: "+b);};a.ca.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,
d,e)};a.ca.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,c).data("isRewritten")};a.ca.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.ca);a.ic=function(){function b(b,c,d,l){b=a.m.Zb(b);for(var e=a.m.Ra,f=0;f<b.length;f++){var h=b[f].key;if(Object.prototype.hasOwnProperty.call(e,h)){var g=e[h];if("function"===typeof g){if(h=g(b[f].value))throw Error(h);
}else if(!g)throw Error("This template engine does not support the '"+h+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.m.ub(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return l.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:"[^"]*"|'[^']*'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{wd:function(b,c,d){c.isTemplateRewritten(b,
d)||c.rewriteTemplate(b,function(b){return a.ic.Kd(b,c)},d)},Kd:function(a,f){return a.replace(c,function(a,c,d,e,h){return b(h,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},ld:function(b,c){return a.aa.Wb(function(d,e){(d=d.nextSibling)&&d.nodeName.toLowerCase()===c&&a.eb(d,b,e)})}}}();a.b("__tr_ambtns",a.ic.ld);(function(){a.B={};a.B.D=function(b){if(this.D=b){var c=a.a.P(b);this.Db="script"===c?1:"textarea"===c?2:"template"==c&&b.content&&11===b.content.nodeType?
3:4}};a.B.D.prototype.text=function(){var b=1===this.Db?"text":2===this.Db?"value":"innerHTML";if(0==arguments.length)return this.D[b];var c=arguments[0];"innerHTML"===b?a.a.dc(this.D,c):this.D[b]=c};var b=a.a.g.Z()+"_";a.B.D.prototype.data=function(c){if(1===arguments.length)return a.a.g.get(this.D,b+c);a.a.g.set(this.D,b+c,arguments[1])};var c=a.a.g.Z();a.B.D.prototype.nodes=function(){var b=this.D;if(0==arguments.length){var e=a.a.g.get(b,c)||{},f=e.jb||(3===this.Db?b.content:4===this.Db?b:q);
if(!f||e.hd)if(e=this.text())f=a.a.Ld(e,b.ownerDocument),this.text(""),a.a.g.set(b,c,{jb:f,hd:!0});return f}a.a.g.set(b,c,{jb:arguments[0]})};a.B.ia=function(a){this.D=a};a.B.ia.prototype=new a.B.D;a.B.ia.prototype.constructor=a.B.ia;a.B.ia.prototype.text=function(){if(0==arguments.length){var b=a.a.g.get(this.D,c)||{};b.jc===q&&b.jb&&(b.jc=b.jb.innerHTML);return b.jc}a.a.g.set(this.D,c,{jc:arguments[0]})};a.b("templateSources",a.B);a.b("templateSources.domElement",a.B.D);a.b("templateSources.anonymousTemplate",
a.B.ia)})();(function(){function b(b,c,d){var e;for(c=a.h.nextSibling(c);b&&(e=b)!==c;)b=a.h.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],h=e.parentNode,g=a.ga.instance,k=g.preprocessNode;if(k){b(e,f,function(a,b){var c=a.previousSibling,d=k.call(g,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.Ua(c,h))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.uc(d,b)});b(e,f,function(b){1!==b.nodeType&&
8!==b.nodeType||a.aa.bd(b,[d])});a.a.Ua(c,h)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,l,m){m=m||{};var h=(b&&d(b)||f||{}).ownerDocument,k=m.templateEngine||g;a.ic.wd(f,k,h);f=k.renderTemplate(f,l,m,h);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");h=!1;switch(e){case "replaceChildren":a.h.ua(b,f);h=!0;break;case "replaceNode":a.a.Wc(b,f);h=!0;break;case "ignoreTargetNode":break;
default:throw Error("Unknown renderMode: "+e);}h&&(c(f,l),m.afterRender&&a.v.K(m.afterRender,null,[f,l[m.as||"$data"]]),"replaceChildren"==e&&a.j.Ga(b,a.j.T));return f}function f(b,c,d){return a.N(b)?b():"function"===typeof b?b(c,d):b}var g;a.ec=function(b){if(b!=q&&!(b instanceof a.ca))throw Error("templateEngine must inherit from ko.templateEngine");g=b};a.bc=function(b,c,l,m,r){l=l||{};if((l.templateEngine||g)==q)throw Error("Set a template engine before calling renderTemplate");r=r||"replaceChildren";
if(m){var h=d(m);return a.$(function(){var g=c&&c instanceof a.fa?c:new a.fa(c,null,null,null,{exportDependencies:!0}),k=f(b,g.$data,g);g=e(m,r,k,g,l);"replaceNode"==r&&(m=g,h=d(m))},null,{Sa:function(){return!h||!a.a.Rb(h)},l:h&&"replaceNode"==r?h.parentNode:h})}return a.aa.Wb(function(d){a.bc(b,c,l,d,"replaceNode")})};a.Pd=function(b,d,g,l,m){function h(b,c){a.v.K(a.a.cc,null,[l,b,n,g,k,c]);a.j.Ga(l,a.j.T)}function k(a,b){c(b,p);g.afterRender&&g.afterRender(b,a);p=null}function n(a,c){p=m.createChildContext(a,
{as:r,noChildContext:g.noChildContext,extend:function(a){a.$index=c;r&&(a[r+"Index"]=c)}});a=f(b,a,p);return e(l,"ignoreTargetNode",a,p,g)}var p,r=g.as,t=!1===g.includeDestroyed||a.options.foreachHidesDestroyed&&!g.includeDestroyed;if(t||g.beforeRemove||!a.Oc(d))return a.$(function(){var b=a.a.c(d)||[];"undefined"==typeof b.length&&(b=[b]);t&&(b=a.a.fb(b,function(b){return b===q||null===b||!a.a.c(b._destroy)}));h(b)},null,{l:l});h(d.w());var u=d.subscribe(function(a){h(d(),a)},null,"arrayChange");
u.l(l);return u};var l=a.a.g.Z(),m=a.a.g.Z();a.f.template={init:function(b,c){c=a.a.c(c());if("string"==typeof c||c.name)a.h.Ea(b);else if("nodes"in c){c=c.nodes||[];if(a.N(c))throw Error('The "nodes" option must be a plain, non-observable array.');var d=c[0]&&c[0].parentNode;d&&a.a.g.get(d,m)||(d=a.a.Xb(c),a.a.g.set(d,m,!0));(new a.B.ia(b)).nodes(d)}else if(c=a.h.childNodes(b),0<c.length)d=a.a.Xb(c),(new a.B.ia(b)).nodes(d);else throw Error("Anonymous template defined, but no template content was provided");
return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var g=c();c=a.a.c(g);d=!0;e=null;"string"==typeof c?c={}:(g=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)));"foreach"in c?e=a.Pd(g||b,d&&c.foreach||[],c,b,f):d?(d=f,"data"in c&&(d=f.createChildContext(c.data,{as:c.as,noChildContext:c.noChildContext,exportDependencies:!0})),e=a.bc(g||b,d,c,b)):a.h.Ea(b);f=e;(c=a.a.g.get(b,l))&&"function"==typeof c.s&&c.s();a.a.g.set(b,l,!f||f.ja&&!f.ja()?q:f)}};a.m.Ra.template=
function(b){b=a.m.Zb(b);return 1==b.length&&b[0].unknown||a.m.Hd(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.h.ea.template=!0})();a.b("setTemplateEngine",a.ec);a.b("renderTemplate",a.bc);a.a.Jc=function(a,c,d){if(a.length&&c.length){var b,f,g,l,m;for(b=f=0;(!d||b<d)&&(l=a[f]);++f){for(g=0;m=c[g];++g)if(l.value===m.value){l.moved=m.index;m.moved=l.index;c.splice(g,1);b=g=0;break}b+=g}}};a.a.Ob=function(){function b(b,d,e,f,g){var c=Math.min,
m=Math.max,k=[],h,n=b.length,p,q=d.length,v=q-n||1,t=n+q+1,u;for(h=0;h<=n;h++){var w=u;k.push(u=[]);var y=c(q,h+v);for(p=m(0,h-1);p<=y;p++)u[p]=p?h?b[h-1]===d[p-1]?w[p-1]:c(w[p]||t,u[p-1]||t)+1:p+1:h+1}c=[];m=[];v=[];h=n;for(p=q;h||p;)q=k[h][p]-1,p&&q===k[h][p-1]?m.push(c[c.length]={status:e,value:d[--p],index:p}):h&&q===k[h-1][p]?v.push(c[c.length]={status:f,value:b[--h],index:h}):(--p,--h,g.sparse||c.push({status:"retained",value:d[p]}));a.a.Jc(v,m,!g.dontLimitMoves&&10*n);return c.reverse()}return function(a,
d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Ob);(function(){function b(b,c,d,l,m){var e=[],f=a.$(function(){var f=c(d,m,a.a.Ua(e,b))||[];0<e.length&&(a.a.Wc(e,f),l&&a.v.K(l,null,[d,f,m]));e.length=0;a.a.gb(e,f)},null,{l:b,Sa:function(){return!a.a.jd(e)}});return{Y:e,$:f.ja()?f:q}}var c=a.a.g.Z(),d=a.a.g.Z();a.a.cc=function(e,f,g,l,m,k){function h(b){x={Aa:b,nb:a.sa(w++)};
u.push(x);v||H.push(x)}function n(b){x=r[b];w!==x.nb.w()&&E.push(x);x.nb(w++);a.a.Ua(x.Y,e);u.push(x)}function p(b,c){if(b)for(var d=0,e=c.length;d<e;d++)a.a.C(c[d].Y,function(a){b(a,d,c[d].Aa)})}f=f||[];"undefined"==typeof f.length&&(f=[f]);l=l||{};var r=a.a.g.get(e,c),v=!r,u=[],t=0,w=0,y=[],A=[],C=[],E=[],H=[],x,I=0;if(v)a.a.C(f,h);else{if(!k||r&&r._countWaitingForRemove){var B=a.a.Mb(r,function(a){return a.Aa});k=a.a.Ob(B,f,{dontLimitMoves:l.dontLimitMoves,sparse:!0})}B=0;for(var F,O,J;F=k[B];B++)switch(O=
F.moved,J=F.index,F.status){case "deleted":for(;t<J;)n(t++);O===q&&(x=r[t],x.$&&(x.$.s(),x.$=q),a.a.Ua(x.Y,e).length&&(l.beforeRemove&&(u.push(x),I++,x.Aa===d?x=null:C.push(x)),x&&y.push.apply(y,x.Y)));t++;break;case "added":for(;w<J;)n(t++);O!==q?(A.push(u.length),n(O)):h(F.value)}for(;w<f.length;)n(t++);u._countWaitingForRemove=I}a.a.g.set(e,c,u);p(l.beforeMove,E);a.a.C(y,l.beforeRemove?a.na:a.removeNode);var L,P;try{var K=e.ownerDocument.activeElement}catch(fa){}if(A.length)for(;(B=A.shift())!=
q;){x=u[B];for(L=q;B;)if((P=u[--B].Y)&&P.length){L=P[P.length-1];break}for(f=0;t=x.Y[f];L=t,f++)a.h.Vb(e,t,L)}B=0;for(A=a.h.firstChild(e);x=u[B];B++){x.Y||a.a.extend(x,b(e,g,x.Aa,m,x.nb));for(f=0;t=x.Y[f];A=t.nextSibling,L=t,f++)t!==A&&a.h.Vb(e,t,L);!x.Dd&&m&&(m(x.Aa,x.Y,x.nb),x.Dd=!0,L=x.Y[x.Y.length-1])}K&&e.ownerDocument.activeElement!=K&&K.focus();p(l.beforeRemove,C);for(B=0;B<C.length;++B)C[B].Aa=d;p(l.afterMove,E);p(l.afterAdd,H)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.cc);a.ba=
function(){this.allowTemplateRewriting=!1};a.ba.prototype=new a.ca;a.ba.prototype.constructor=a.ba;a.ba.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9>a.a.W?0:b.nodes)?b.nodes():null)return a.a.la(c.cloneNode(!0).childNodes);b=b.text();return a.a.ta(b,e)};a.ba.Na=new a.ba;a.ec(a.ba.Na);a.b("nativeTemplateEngine",a.ba);(function(){a.Za=function(){var a=this.Gd=function(){if(!u||!u.tmpl)return 0;try{if(0<=u.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(d){}return 1}();this.renderTemplateSource=
function(b,c,f,g){g=g||w;f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var d=b.data("precompiled");d||(d=b.text()||"",d=u.template(null,"{{ko_with $item.koBindingContext}}"+d+"{{/ko_with}}"),b.data("precompiled",d));b=[c.$data];c=u.extend({koBindingContext:c},f.templateOptions);c=u.tmpl(d,b,c);c.appendTo(g.createElement("div"));u.fragments={};return c};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+
a+" })()) }}"};this.addTemplate=function(a,b){w.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(u.tmpl.tag.ko_code={open:"__.push($1 || '');"},u.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Za.prototype=new a.ca;a.Za.prototype.constructor=a.Za;var b=new a.Za;0<b.Gd&&a.ec(b);a.b("jqueryTmplTemplateEngine",a.Za)})()})})()})();
